config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/jobs', to: 'jobs#index', as: 'jobs'

  get '/jobs/new', to: 'jobs#new', as: 'new_job'
  post '/jobs', to: 'jobs#create' # already has a name    

  get '/jobs/:id', to: 'jobs#show', as: 'job'

  get '/jobs/:id/edit', to: 'jobs#edit', as: 'edit_job'
  patch 'jobs/:id', to: 'jobs#update'

  delete  'jobs/:id', to: 'jobs#destroy', as: 'delete_job'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index 
    @jobs = Job.all.order(:id)
  end

  def show 
    @job = Job.find_by(id: params[:id])

    if @job.nil?
      redirect_to jobs_path
    end
  end

  def new 
    @job = Job.new
  end

  def create 
    @job = Job.new(
      title: params[:job][:title],
      description: params[:job][:description],
      company: params[:job][:company]
    )
    if @job.save
      redirect_to jobs_path # goes all the way through the request cycle again
    else
      render :new # take whatever data the controller currently has and send only that data back to the browser; we want to hang on to the current job object
    end
  end

  def edit
    @job = Job.find_by(id: params[:id])
  end

  def update
    @job = Job.find_by(id: params[:id])
    is_successful = @job.update(
      {
        title: params[:job][:title],
        description: params[:job][:description],
        company: params[:job][:company]
      }
    )

    if is_successful
      redirect_to job_path(@job.id) # OR params[:id]
    else
      # if unsuccessful, stays on the edit form
      render :edit
    end
  end

  def destroy
    # we only need instance variables when they are accessed in a view external from the controller.

    # If we're not accessing variables inside of a view, they should not be instance variables

    job = Job.find_by(id: params[:id])

    if job.destroy 
      redirect_to jobs_path
    else 
    end

  end

  private
  
  def job_params
    return params.require(:job).permit(:title, :description, :company)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<h3> Edit Job </h3>

<%= form_with model: @job do |f| %>
  <%= f.label :title %> 
  <%= f.text_field :title %>
  <br/>
  <%= f.label :description %> 
  <%= f.text_area :description %>
  <br/>
  <%= f.label :company %> 
  <%= f.text_field :company %>
  <br/>
  <%= f.submit %>
<% end %>

app/views/jobs/index.html.erb
<h1> Job Board </h1>

<% @jobs.each do |job| %> <%# Code tags %>
  <div class="job"> 
    <strong>
      <%= link_to job.title, job_path(job.id) %>
    </strong>
    <br/>
  </div>
<% end %>
<br/>
<%= link_to 'Add Job', new_job_path %>

app/views/jobs/new.html.erb
<h3> Add a Job </h3>

<%# gives ability to use Rails conventions for its standard CRUD operations on an Active Record model object => Job model %>
<%= form_with model: @job do |f| %>
  <%= f.label :title %> 
  <%= f.text_field :title %>
  <br/>
  <%= f.label :description %> 
  <%= f.text_area :description %>
  <br/>
  <%= f.label :company %> 
  <%= f.text_field :company %>
  <br/>
  <%= f.submit %>
<% end %>

app/views/jobs/show.html.erb
<h2> Job Details </h2>
<%# <p>TODO: Add a real job</p> %>

<div>
  <strong><%= @job.title %></strong> at <strong><%= @job.company%></strong>
  <p><%= @job.description %></p>
  <%= link_to "Home", jobs_path %>
  &nbsp
  <%= link_to "Edit Job", edit_job_path(@job.id) %>
  &nbsp
  <%= link_to "Delete Job", delete_job_path(@job.id), method: :delete, data: {confirm: "Are you sure?"} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsJobBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>